### ISSUE TITLE
.cnt files do classification tasks

### ISSUE THREAD

**Issue by upper127** [935963004/LaBraM#17]
If the dataset is a cnt file, what code needs to be used or written to use the model?I seem to be seeing a couple of preprocessed python scripts:make_h5dataset_for_pretrain.py、dataset.py. Do I just modify the folder path and run it directly, or do I need to write my own code? If I need to write my own code, what do I need to pay attention to? I've seen a lot of people have questions about how to run the model on their own dataset, can you provide some help? Thank you

**Comment by 935963004** [comment]
You can use make_h5dataset_for_pretrain.py to transform .cnt files into .hdf5 files for pre-training.  If you want to run finetuning to perform classification tasks with your own dataset, you are recommended to use the provided finetuning script in README. For your own dataset, you should write preprocessing and dataloader codes by your own, and replace the dataloader part in run_class_finetuning.py with yours.

**Comment by upper127** [comment]
Is it necessary to execute modeling_pretrain.py or can I run run_class_finetuning.py directly after writing the preprocessing and data loading code?

**Comment by 935963004** [comment]
It depends on you. You can load our provided pre-trained checkpoint, and fine-tune it on your own dataset. If you find the performance unsatisfactory, you can also try to pre-train a new model using your own dataset.

**Comment by upper127** [comment]
Just remove the useless channels from the cnt file, filter between 0.1 Hz and 75 Hz, trap filter at 50 Hz, resample to 200 Hz, and then divide the training set validation set test set, and change the data loader in the code and then the classification task will be achieved?

**Comment by 935963004** [comment]
Right

**Comment by upper127** [comment]
Is there a format requirement for the data input to the model? Simply put, can I input the cnt file directly into the model, or do I need to do what I did with the TUEV data: convert the edf format to pkl format?Thanks

**Comment by upper127** [comment]
def BuildEvents(signals, times, EventData):
    [numEvents, z] = EventData.shape
    fs = 200.0
    [numChan, numPoints] = signals.shape
    features = np.zeros([numEvents, numChan, int(fs) * 5])
    offending_channel = np.zeros([numEvents, 1])  # channel that had the detected thing
    labels = np.zeros([numEvents, 1])
    offset = signals.shape[1]
    signals = np.concatenate([signals, signals, signals], axis=1)
    for i in range(numEvents):  # for each event
        chan = int(EventData[i, 0])  # chan is channel
        start = np.where((times) >= EventData[i, 1])[0][0]
        end = np.where((times) >= EventData[i, 2])[0][0]
        print("offset:", offset)
        print("start:", start)
        print("end:", end)
        print("start index in signals:", offset + start - int(fs))
        print("end index in signals:", offset + end )
        # print("Shape of features array before assignment:", features.shape)
        print(offset + start - int(fs), offset + end , signals.shape)
        features[i, :] = signals[:, offset + start - int(fs) : offset + end + ]
        # features[i, :] = signals[:, offset + start: offset]  #特征切片，开始前2s到结束 -2~8 确保shape（68，1000）
        offending_channel[i, :] = int(chan)
        # print("Shape of EventData array:", EventData.shape)
        # print("EventData example:", EventData[0])
        # print("eventdata",EventData)
        # labels[i, :] = int(EventData[i, 3])
        labels[i, :] = int(EventData[i, 2])   #  Eventdata的第二列才是标签信息【1 2 3 4】
    return [features, offending_channel, labels]
    
[Parallel(n_jobs=1)]: Done  17 tasks      | elapsed:    0.1s
[Parallel(n_jobs=5)]: Using backend LokyBackend with 5 concurrent workers.
[Parallel(n_jobs=5)]: Done  13 tasks      | elapsed:    0.6s
[Parallel(n_jobs=5)]: Done  68 out of  68 | elapsed:    1.2s finished
Used Annotations descriptions: ['1', '2', '3', '4']
offset: 100912
start: 0
end: 800
start index in signals: 100712
end index in signals: 101712
100712 101712 (68, 302736)
offset: 100912
start: 0
end: 600
start index in signals: 100712
end index in signals: 101512
100712 101512 (68, 302736)
0it [00:05, ?it/s]
Traceback (most recent call last):
  File "E:\lab\DL\LaBraM-main\dataset_maker\make_MI.py", line 128, in <module>
    load_up_objects(
  File "E:\lab\DL\LaBraM-main\dataset_maker\make_MI.py", line 90, in load_up_objects
    signals, offending_channels, labels = BuildEvents(signals, times, events)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\lab\DL\LaBraM-main\dataset_maker\make_MI.py", line 62, in BuildEvents
    features[i, :] = signals[:, offset + start - int(fs): offset + end ]
    ~~~~~~~~^^^^^^
ValueError: could not broadcast input array from shape (68,800) into shape (68,1000)

在仿写预处理的时候我不太理解这个特征切片是什么，按1000长度的要求修改之后，似乎在下一次切片还是发生了异常

**Comment by Enzo2357** [comment]
您好，我也在跑labram，可以交流一下吗

**Comment by upper127** [comment]
> 您好，我也在跑labram，可以交流一下吗

我还没跑起来

**Comment by Enzo2357** [comment]
> > 您好，我也在跑labram，可以交流一下吗
> 
> 我还没跑起来

我也没跑起来，中途遇到了些问题，咱们可以交流以下吗

**Comment by upper127** [comment]
q1950954349
