### ISSUE TITLE
'RelativePositionBias' is lost

### ISSUE THREAD

**Issue by dongliang0** [935963004/LaBraM#25]
Traceback (most recent call last):
  File "/root/autodl-tmp/LaBraM/run_labram_pretraining.py", line 28, in <module>
    import modeling_pretrain
  File "/root/autodl-tmp/LaBraM/modeling_pretrain.py", line 16, in <module>
    from modeling_finetune import Block, _cfg, PatchEmbed, RelativePositionBias
ImportError: cannot import name 'RelativePositionBias' from 'modeling_finetune' (/root/autodl-tmp/LaBraM/modeling_finetune.py)

There is not 'RelativePositionBias' in modeling_finetune.py. How to solve?

**Comment by 935963004** [comment]
Thanks for your question. I have fixed this bug by deleting this useless part of code.
